INSERT INTO dinos (name, height, length) VALUES ('Allosaurus', 5, 12);
INSERT INTO dinos (name, height, length) VALUES ('Apatosaurus', 5, 23);
INSERT INTO dinos (name, height, length) VALUES ('Argentinosaurus', 21, 37);
INSERT INTO dinos (name, height, length) VALUES ('Brachiosaurus', 15, 31);
INSERT INTO dinos (name, height, length) VALUES ('Ceratosaurus', 4, 6);
INSERT INTO dinos (name, height, length) VALUES ('Megalosaurus', 4, 8);
INSERT INTO dinos (name, height, length) VALUES ('Oviraptor', 1, 2);
INSERT INTO dinos (name, height, length) VALUES ('Tyrannosaurus', 7, 15);
INSERT INTO dinos (name, height, length) VALUES ('Velociraptor', 1, 2);